# Site Settings
title:               Phoenix@BioHub Home
tagline:             The place where Biology meets SuperComputers
description:         Phoenix@BioHub
collections:
  announcements:
    output:      true
    permalink:   /:categories/:title/
  downloads:
    output:      true
    permalink:   /:categories/:title/
baseurl:             "/Phoenix-BioHub-Support"
url:                 "https://robqiao.github.io"
github:
  url:               #"https://github.com/robqiao/Phoenix-BioHub-Support"
author:
  name:              "Robert Qiao"
  email:             "robert.qiao@adelaide.edu.au"
  twitter:           "robqiao"
  instagram:         #""
  facebook:          #""
  github:            "robqiao"
  linkedin:          "robqiao"
navigation:
- title: About Us
  url: /aboutus
- title: News
  url: /announcements
- title: Blogs
  url: /blogs
- title: Downloads
  url: /downloads
- title: Contact Us
  url: /contactus

paginate:            5
disqus:              "robqiao"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:	     none
plugins:             [jekyll-paginate, jekyll-feed, jekyll-email-protect]
