# Site Settings
title:               Phoenix@BioHub Home
tagline:             The place where Biology meets SuperComputers
description:         Phoenix@BioHub
baseurl:             "/Phoenix-BioHub-Support"
url:                 "https://robqiao.github.io"
github:
  url:               #"https://github.com/robqiao/Phoenix-BioHub-Support"
author:
  name:              "Robert Qiao"
  email:             "robert.qiao@adelaide.edu.au"
  twitter:           "robqiao"
  instagram:         #""
  facebook:          #""
  github:            "robqiao"
  linkedin:          "robqiao"
navigation:
- title: About Us
  url: /aboutus
- title: News
  url: /announcements
- title: Blogs
  url: /blogs
- title: Downloads
  url: /downloads
- title: Contact Us
  url: /contactus

# Plugins
paginate:            5
disqus:              "robqiao"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:	     none
<<<<<<< HEAD
=======
<<<<<<< HEAD
<<<<<<< HEAD
plugins:	     [jekyll-paginate, jekyll-email-protect, jekyll-sitemap, jekyll-feed]		

# Jekyll feed settings
=======
=======
>>>>>>> parent of a0d4654... backend update + atom feed function
>>>>>>> a3820a26e74cbbc9a6205c76eabbe9b01480b9aa
gems:		     [jekyll-paginate, jekyll-email-protect]		
plugins_dir:
   - jekyll-feed
   - jekyll-email-protect
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> parent of a0d4654... backend update + atom feed function
=======
>>>>>>> parent of a0d4654... backend update + atom feed function
>>>>>>> a3820a26e74cbbc9a6205c76eabbe9b01480b9aa

# Where things are
layouts_dir: _layouts
destination: ./_site
includes_dir: _includes
collections:
  announcements:
    output:      true
    permalink:   /:categories/:title/
  downloads:
    output:      true
    permalink:   /:categories/:title/
