# Site Settings
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:	     none
plugins:	     [jekyll-paginate, jekyll-email-protect, jekyll-sitemap, jekyll-feed]		

# Jekyll feed settings
title:               "{{ site.data.settings.title }} | {{ site.data.settings.tagline }}"

# Where things are
layouts_dir: _layouts
destination: ./_site
includes_dir: _includes
collections:
  announcements:
    output:      true
    permalink:   /:categories/:title/
  downloads:
    output:      true
    permalink:   /:categories/:title/
