# Site Settings
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
plugins:	     
 - jekyll-paginate
 - jekyll-sitemap
 - jekyll-feed		

#plugins:	     [jekyll-paginate, jekyll-email-protect, jekyll-sitemap, jekyll-feed]		

# Feed settings
title:               "{{ site.data.settings.title }} | {{ site.data.settings.tagline }}"

# Where things are
layouts: _layouts
destination: ./_site
includes: _includes
collections:
  announcements:
    output:      true
    permalink:   /:categories/:title/
  downloads:
    output:      true
    permalink:   /:categories/:title/
