title:          "Phoenix@BioHub Home"
tagline:        "The place where Biology meets SuperComputers"
baseurl:        "/Phoenix-BioHub-Support"
url:            "https://robqiao.github.io"

menu:
- {name: 'About Us', url: 'aboutus.html'}
- {name: 'News', url: 'announcements.html'}
- {name: 'Blogs', url: 'blogs.html'}
- {name: 'Downloads', url: 'downloads.html'}
- {name: 'Contact Us', url: 'contactus.html'}

social:
- {icon: 'github', link: 'https://github.com/robqiao/Phoenix-BioHub-Support'}
- {icon: 'twitter', link: 'https://twitter.com/robqiao'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/robqiao/'}
- {icon: 'envelope', link: 'mailto:robert.qiao@adelaide.edu.au'}
- {icon: 'rss-square', link: 'https://robqiao.github.io/Phoenix-BioHub-Support/feed.xml'}
# Available social icons are powered by Font Awesome, so you can use any icon that they offer

# Plugins
disqus:              "robqiao"
google-ID:	     "UA-104989198-1"
